#MICx AimLead configuration
#Tue Sep 01 19:53:03 CST 2026
autoPing=true
drawLink=true
extraMs=100
fireDot=true
gameRtt=true
manualPing=250
markerOffsetX=0
markerOffsetY=6
markerScaleX=1.0
markerScaleY=1.0
maxGhosts=4
minDist=12
renderGhost=true
serverShadow=false
zombiesOnly=true
