#MICx KeyboardClicker configuration
#Sun Sep 27 00:06:52 CST 2026
clickIntervalMs=50
jamExemptEnabled=true
jamProtectModeB=false
mode23=true
mode234=true
mode24=false
mode34=false
modeKey=86
rightClickTrigger=false
threatRange=4.0
toggleKey=96
