#MICx Magnet
#Thu Aug 27 22:53:28 CST 2026
headshotStopDeg=1.5
hitboxOnly=true
includeGiant=false
includeGolem=false
includeSlime=false
pullStrength=0.4
radiusDeg=8.0
slowFactor=0.5
slowMode=false
toggleKey=-97
toggleKeys=-97
zombiesOnly=false
