#MICx Magnet
#Wed Sep 23 01:26:17 CST 2026
headshotStopDeg=1.5
hitboxOnly=true
includeGiant=false
includeGolem=false
includeSlime=false
pullStrength=0.4
radiusDeg=8.0
slowFactor=0.5
slowMode=false
toggleKey=0
toggleKeys=
zombiesOnly=false
