#MICx Toolkit module states
#Mon Sep 28 02:09:28 CST 2026
aim_lead=true
aimbot=true
aimbot_hud=true
anti_axe=false
anti_reshift=true
asr=true
auto_hide_visuals=true
auto_text=true
auto_update=true
chams=true
chat_cleaner=true
chat_copy=true
chat_message_translate=true
chat_translate=false
dps_counter=true
eco_rate=true
esp=false
fullbright=true
golem_marker=true
keyboard_clicker=true
last_mobs=false
legacy_sneak_visuals=true
lr_indicator=true
magnet=false
noreload=false
packet_log=false
particle_free=true
player_outline_esp=true
player_visibility=true
rank_spoof=false
rank_up_tool=false
remote_shop=true
revive_aura=false
right_clicker=true
round_timer=true
skill_cast=true
slime_forecast=true
spawn_marker=true
sword_block=false
team_sync=true
teammate_hp=true
toggle_sprint=true
toro_health=true
view_hold=true
wave_spawn_sound=true
welcome=true
window_spawn_counter=true
zombie_fade=true
zombies_assist=true
zombies_explorer=true
zoom_scope=true
