#MICx TeammateHP configuration
#Wed Sep 09 19:54:20 CST 2026
bgAlpha=70
cardWidth=180
keyCode=72
overlayEnabled=true
reviveHoloB=true
screenX=8
screenY=40
showDistance=true
showHidden=false
uiScale=1.0
