#MICx TeamSync configuration
#Wed Sep 23 21:06:26 CST 2026
hudRightOffset=263
hudScaleX=1.0
hudScaleY=1.0
hudY=0
localAimFallback=true
pingButton=-1
renderOverlay=true
renderWorld=true
rosterCheckMs=1000
serverUrl=wss\://zombie.nienie.fun/zombies/ws
showPing=true
toggleKeyCode=74
tokenUrl=https\://zombie.nienie.fun/zombies/token
updateIntervalMs=250
