#MICx ToroHealth configuration
#Tue Sep 01 19:53:03 CST 2026
damageColor=352320
displayMode=0
displayPosition=5
displayX=0
displayY=0
healColor=7882280
hideDelayMs=200
hudScaleX=1.0
hudScaleY=1.0
overlayEnabled=true
showDamageParticles=true
