#MICx ZombiesAssist configuration
#Tue Sep 01 19:53:03 CST 2026
autoNotices=true
blockAlert=true
blockAlertScale=1.0
blockAlertXOffset=0
blockAlertYOffset=14
ecoClockBottom=8
ecoClockRight=4
ecoClockScale=1.0
ecoHints=true
ecoHudCenterYOffset=0
ecoHudRight=4
ecoHudScale=1.0
frCoach=true
frHudScale=1.0
frHudXOffset=0
frHudYOffset=48
lsAssist=true
lsHudScale=1.0
lsHudXOffset=159
lsHudYOffset=43
noRotate=true
originalScoreboard=false
overlayEnabled=true
pcRoundInfo=false
postGameStats=true
puBeam=true
puHudBottom=6
puHudRight=4
puHudScale=1.0
roundsRecord=ALL
showEconomy=true
showMobs=true
showPowerups=true
showSplitOnWaveTable=true
showStats=true
slimeGrowth=true
specialThreatHud=true
speedrunEnabled=true
tacticalHudRight=0
tacticalHudScale=1.0
tacticalHudY=38
threatHudScale=1.0
threatHudXOffset=18
threatHudYOffset=8
tooAlert=true
tooRushAlert=true
tooRushScale=1.0
tooRushXOffset=-2
tooRushYOffset=-39
tooSpawnAlert=true
tooSpawnDistance=15
tooSpawnScale=2.0
tooSpawnXOffset=0
tooSpawnYOffset=-28
tooStrictGreen=true
topHudScale=1.0
topHudXOffset=12
topHudY=0
waveTableHud=true
waveTableHudDx=577
waveTableHudDy=270
waveTempo=true
